### ISSUE TITLE
unresolved external symbols

### ISSUE THREAD

**Issue by Doomboom589** [FFuuZZuu/deya#1]
https://pastebin.com/pjy3wsen

**Comment by FFuuZZuu** [comment]
Thank you for the issue. For future reference we now have issue templates that you can use instead of just pasting in the logs.

**Comment by FFuuZZuu** [comment]
Looks like a Windows specific error, so I will have a look once I have a chance to setup my windows VM for testing.

**Comment by FFuuZZuu** [comment]
Can you try this again, I have gone through and fixed alot of issues with the premake aswell as switching to a static library, so it may work now.

**Comment by Doomboom589** [comment]
still doesnt work, new log here: https://pastebin.com/JRjqeyVA

**Comment by Doomboom589** [comment]
after cleaning deya and sandbox, here is the new log: https://pastebin.com/E8rvJUP6

**Comment by DokuseiSan** [comment]
FIX: Open GLFW project `properties >> C/C++ >> Code Generation` and set the `Runtime Library` property to `/MT`

**Comment by FFuuZZuu** [comment]
During the swap to statically linking, it seems I forgot to push the submodules to their respective repos. My local repo of deya didnt have these issues due to the fact I edited the submodules locally. Thanks for noticing this.

**Comment by FFuuZZuu** [comment]
I have implemented a fix for this issue, @DokuseiSan, is it possible you could check if this works so I can close this?

**Comment by FFuuZZuu** [comment]
Or @Doomboom589?

**Comment by Doomboom589** [comment]
no more issues when running
